name: Security Scan

on: [push]

jobs:
  semgrep_sast_scan:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep Scan
        uses: semgrep/semgrep-action@v1
        with:
          config: auto

      - name: Upload Semgrep results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
